apiVersion: v1
kind: Namespace
metadata:
	name: apg-payment
	labels:
		name: apg-payment
		tier: payment-processing
		environment: production
		owner: datacraft
	annotations:
		description: "APG Payment Gateway namespace for all payment processing services"

---
apiVersion: v1
kind: ResourceQuota
metadata:
	name: payment-gateway-quota
	namespace: apg-payment
spec:
	hard:
		requests.cpu: "2"
		requests.memory: 4Gi
		limits.cpu: "8"
		limits.memory: 16Gi
		persistentvolumeclaims: "10"
		services: "20"
		secrets: "20"
		configmaps: "20"

---
apiVersion: v1
kind: LimitRange
metadata:
	name: payment-gateway-limits
	namespace: apg-payment
spec:
	limits:
	- default:
		cpu: "500m"
		memory: "1Gi"
	defaultRequest:
		cpu: "100m"
		memory: "256Mi"
	type: Container