apiVersion: v1
kind: Secret
metadata:
	name: payment-gateway-secrets
	namespace: apg-payment
type: Opaque
stringData:
	database-url: "postgresql://payment_user:CHANGE_IN_PRODUCTION@postgres-service:5432/payment_gateway_db"
	redis-url: "redis://redis-service:6379/0"
	secret-key: "CHANGE_THIS_SECRET_KEY_IN_PRODUCTION"

---
apiVersion: v1
kind: Secret
metadata:
	name: payment-processor-secrets
	namespace: apg-payment
type: Opaque
stringData:
	# MPESA Configuration
	mpesa-consumer-key: "YOUR_MPESA_CONSUMER_KEY"
	mpesa-consumer-secret: "YOUR_MPESA_CONSUMER_SECRET"
	mpesa-passkey: "YOUR_MPESA_PASSKEY"
	mpesa-shortcode: "YOUR_MPESA_SHORTCODE"
	
	# Stripe Configuration
	stripe-secret-key: "sk_live_YOUR_STRIPE_SECRET_KEY"
	stripe-publishable-key: "pk_live_YOUR_STRIPE_PUBLISHABLE_KEY"
	stripe-webhook-secret: "whsec_YOUR_STRIPE_WEBHOOK_SECRET"
	
	# PayPal Configuration
	paypal-client-id: "YOUR_PAYPAL_CLIENT_ID"
	paypal-client-secret: "YOUR_PAYPAL_CLIENT_SECRET"
	
	# Adyen Configuration
	adyen-api-key: "YOUR_ADYEN_API_KEY"
	adyen-merchant-account: "YOUR_ADYEN_MERCHANT_ACCOUNT"
	adyen-environment: "live"

---
apiVersion: v1
kind: ConfigMap
metadata:
	name: payment-gateway-config
	namespace: apg-payment
data:
	# Application Configuration
	FLASK_ENV: "production"
	LOG_LEVEL: "INFO"
	
	# Payment Configuration
	PAYMENT_TIMEOUT: "30"
	MAX_RETRY_ATTEMPTS: "3"
	
	# ML Model Configuration
	FRAUD_DETECTION_THRESHOLD: "0.8"
	MODEL_UPDATE_INTERVAL: "3600"
	
	# Cache Configuration
	CACHE_TTL: "300"
	
	# Rate Limiting
	RATE_LIMIT_PER_MINUTE: "100"
	RATE_LIMIT_BURST: "20"