"""Integration API Management APG capability package."""

from __future__ import annotations

from .api import (
	AnalyticsApi,
	APIManagementApi,
	ConsumerManagementApi,
	GatewayApi,
	approve_api,
	attach_policy,
	capability_status,
	create_record,
	create_subscription,
	dashboard_summary,
	deploy_api,
	issue_api_key,
	list_records,
	record_usage,
	register_api,
	register_api_agent,
	register_api_endpoints,
	register_consumer,
	register_endpoint,
	service,
)
from .capability_contract import CAPABILITY_ID, CAPABILITY_NAME, CAPABILITY_VERSION, evaluate_capability_rules, get_capability_contract
from .service import (
	APIManagementError,
	APINotFoundError,
	APILifecycleService,
	AnalyticsService,
	APIService,
	AuthenticationError,
	AuthorizationError,
	ConsumerManagementService,
	ConsumerNotFoundError,
	IntApiService,
	PolicyManagementService,
	RateLimitExceededError,
)


__capability_info__ = {
	"capability_id": CAPABILITY_ID,
	"capability_name": CAPABILITY_NAME,
	"capability_code": "INT_API",
	"version": CAPABILITY_VERSION,
	"category": "integration",
	"description": "Composable API registry, gateway governance, consumer, policy, deployment, analytics, and API-agent lifecycle capability.",
	"provides": [
		"api_registry_lifecycle",
		"api_endpoint_lifecycle",
		"api_policy_lifecycle",
		"api_consumer_lifecycle",
		"api_deployment_workflow",
		"api_agents",
	],
}

__version__ = CAPABILITY_VERSION

__all__ = [
	"AnalyticsApi",
	"AnalyticsService",
	"APIManagementApi",
	"APIManagementError",
	"APINotFoundError",
	"APILifecycleService",
	"APIService",
	"AuthenticationError",
	"AuthorizationError",
	"CAPABILITY_ID",
	"CAPABILITY_NAME",
	"CAPABILITY_VERSION",
	"ConsumerManagementApi",
	"ConsumerManagementService",
	"ConsumerNotFoundError",
	"GatewayApi",
	"IntApiService",
	"PolicyManagementService",
	"RateLimitExceededError",
	"__capability_info__",
	"__version__",
	"approve_api",
	"attach_policy",
	"capability_status",
	"create_record",
	"create_subscription",
	"dashboard_summary",
	"deploy_api",
	"evaluate_capability_rules",
	"get_capability_contract",
	"issue_api_key",
	"list_records",
	"record_usage",
	"register_api",
	"register_api_agent",
	"register_api_endpoints",
	"register_consumer",
	"register_endpoint",
	"service",
]
