# APG Accounts Receivable - Kubernetes Secrets
# Note: In production, use external secret management (HashiCorp Vault, AWS Secrets Manager, etc.)

apiVersion: v1
kind: Secret
metadata:
  name: apg-ar-database-secret
  namespace: apg-ar
  labels:
    app.kubernetes.io/name: apg-accounts-receivable
    app.kubernetes.io/component: database
type: Opaque
data:
  # Base64 encoded values - replace with actual production secrets
  username: YXJfdXNlcg==  # ar_user
  password: YXJfcGFzc3dvcmQ=  # ar_password
  database: YXBnX2Fy  # apg_ar
  host: cG9zdGdyZXMtc2VydmljZQ==  # postgres-service
  port: NTQzMg==  # 5432

---
apiVersion: v1
kind: Secret
metadata:
  name: apg-ar-redis-secret
  namespace: apg-ar
  labels:
    app.kubernetes.io/name: apg-accounts-receivable
    app.kubernetes.io/component: cache
type: Opaque
data:
  # Base64 encoded values
  password: cmVkaXNfcGFzc3dvcmQ=  # redis_password
  host: cmVkaXMtc2VydmljZQ==  # redis-service
  port: NjM3OQ==  # 6379

---
apiVersion: v1
kind: Secret
metadata:
  name: apg-ar-app-secret
  namespace: apg-ar
  labels:
    app.kubernetes.io/name: apg-accounts-receivable
    app.kubernetes.io/component: application
type: Opaque
data:
  # Base64 encoded values - generate strong secrets in production
  secret-key: WW91ci1TZWNyZXQtS2V5LUhlcmU=  # Your-Secret-Key-Here
  jwt-secret-key: WW91ci1KV1QtU2VjcmV0LUtleS1IZXJl  # Your-JWT-Secret-Key-Here
  encryption-key: WW91ci1FbmNyeXB0aW9uLUtleS1IZXJl  # Your-Encryption-Key-Here

---
apiVersion: v1
kind: Secret
metadata:
  name: apg-ar-ai-service-secret
  namespace: apg-ar
  labels:
    app.kubernetes.io/name: apg-accounts-receivable
    app.kubernetes.io/component: ai-services
type: Opaque
data:
  # APG AI service API keys - base64 encoded
  federated-learning-api-key: ZmVkLWxlYXJuaW5nLWFwaS1rZXk=  # fed-learning-api-key
  ai-orchestration-api-key: YWktb3JjaGVzdHJhdGlvbi1hcGkta2V5  # ai-orchestration-api-key
  time-series-analytics-api-key: dGltZS1zZXJpZXMtYW5hbHl0aWNzLWFwaS1rZXk=  # time-series-analytics-api-key

---
apiVersion: v1
kind: Secret
metadata:
  name: apg-ar-monitoring-secret
  namespace: apg-ar
  labels:
    app.kubernetes.io/name: apg-accounts-receivable
    app.kubernetes.io/component: monitoring
type: Opaque
data:
  # Grafana admin password
  grafana-admin-password: YWRtaW4xMjM=  # admin123
  
  # Prometheus basic auth (if enabled)
  prometheus-username: cHJvbWV0aGV1cw==  # prometheus
  prometheus-password: cHJvbWV0aGV1c19wYXNzd29yZA==  # prometheus_password