"""APG connector CLI commands."""
import click
from pathlib import Path
from rich.console import Console
from rich.table import Table

console = Console()


@click.group()
def connector():
	"""Manage APG external service connectors."""
	pass


@connector.command("generate")
@click.option("--spec", required=True, type=click.Path(exists=True), help="OpenAPI 3.x YAML or JSON spec file")
@click.option("--output", default=None, help="Output Python file (default: <spec-stem>_connector.py)")
@click.option("--class-name", default=None, help="Connector class name override")
def generate(spec: str, output: str | None, class_name: str | None) -> None:
	"""Generate a Python connector stub from an OpenAPI spec."""
	try:
		from compiler.connector_generator import generate_connector_stub
		code = generate_connector_stub(spec, output, class_name)
		out_path = output or Path(spec).with_name(Path(spec).stem + "_connector.py")
		console.print(f"[green]Generated connector: {out_path}[/green]")
		# Count operations: subtract __init__, _call, health_check
		op_count = code.count("    def ") - 3
		console.print(f"   {max(0, op_count)} operations stubbed")
	except Exception as e:
		console.print(f"[red]Error: {e}[/red]")
		raise SystemExit(1)


@connector.command("list")
@click.option("--dir", "scan_dir", default="connectors", help="Directory to scan for connector files")
def list_connectors(scan_dir: str) -> None:
	"""List discovered connectors in the connectors/ directory."""
	from compiler.connector_generator import scan_connectors
	manifests = scan_connectors(scan_dir)
	if not manifests:
		console.print("[yellow]No connectors found.[/yellow]")
		console.print(f"  Generate one: apg connector generate --spec openapi.yaml")
		return
	table = Table(title=f"APG Connectors ({scan_dir}/)")
	table.add_column("Name", style="cyan")
	table.add_column("Title")
	table.add_column("Operations", justify="right")
	table.add_column("File")
	for m in manifests:
		table.add_row(
			m.get("name", ""),
			m.get("title", ""),
			str(len(m.get("operations", []))),
			m.get("file", ""),
		)
	console.print(table)


@connector.command("scaffold")
@click.argument("name")
@click.option("--base-url", default="https://api.example.com", help="API base URL")
@click.option("--operations", default="create,list,get,update,delete", help="Comma-separated operation names")
@click.option("--output", default=None, help="Output directory (default: connectors/)")
def scaffold(name: str, base_url: str, operations: str, output: str | None) -> None:
	"""Scaffold a new connector stub without an OpenAPI spec."""
	import re

	ops = [o.strip() for o in operations.split(",") if o.strip()]
	class_name = "".join(p.capitalize() for p in re.split(r"[\s\-_]+", name) if p) + "Connector"
	out_dir = Path(output or "connectors")
	out_dir.mkdir(parents=True, exist_ok=True)
	out_file = out_dir / f"{name.lower().replace('-', '_')}_connector.py"

	lines = [
		'"""APG connector stub for ' + name + '.',
		'',
		'Scaffold generated by: apg connector scaffold ' + name,
		'Implement the _call method or override individual operations.',
		'"""',
		'from __future__ import annotations',
		'from typing import Any',
		'',
		'',
		'class ' + class_name + ':',
		'    BASE_URL: str = ' + repr(base_url),
		'    TIMEOUT: int = 30',
		'    CIRCUIT_THRESHOLD: int = 5',
		'',
		'    MANIFEST: dict[str, Any] = {',
		'        "name": ' + repr(class_name) + ',',
		'        "title": ' + repr(name) + ',',
		'        "base_url": ' + repr(base_url) + ',',
		'        "operations": ' + repr(ops) + ',',
		'    }',
		'',
		'    def __init__(self, base_url: str | None = None, auth_header: str | None = None) -> None:',
		'        self._base_url = (base_url or self.BASE_URL).rstrip("/")',
		'        self._auth_header = auth_header',
		'        self._failures = 0',
		'',
		'    def health_check(self) -> bool:',
		'        return self._failures < self.CIRCUIT_THRESHOLD',
		'',
	]
	for op in ops:
		lines += [
			'    def ' + op + '(self, payload: dict[str, Any] | None = None) -> dict[str, Any]:',
			'        raise NotImplementedError("' + op + ' not implemented")',
			'',
		]
	lines += [
		'',
		'import os as _os',
		'_default_' + name.lower().replace("-", "_") + '_connector = ' + class_name + '()',
	]

	out_file.write_text("\n".join(lines), encoding="utf-8")
	console.print(f"[green]Scaffolded connector: {out_file}[/green]")
	console.print(f"   Class: {class_name}")
	console.print(f"   Operations: {', '.join(ops)}")
