# APG Time & Attendance Capability - Configuration
# Copyright © 2025 Datacraft

apiVersion: v1
kind: ConfigMap
metadata:
  name: time-attendance-config
  namespace: apg-time-attendance
  labels:
    app.kubernetes.io/name: apg-time-attendance
    app.kubernetes.io/component: configmap
data:
  # Application Configuration
  ENVIRONMENT: "production"
  TRACKING_MODE: "comprehensive"
  LOG_LEVEL: "INFO"
  
  # Database Configuration
  DATABASE_HOST: "postgres-primary"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "time_attendance_db"
  DATABASE_POOL_SIZE: "20"
  DATABASE_MAX_OVERFLOW: "30"
  DATABASE_POOL_TIMEOUT: "30"
  
  # Redis Configuration
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # Feature Flags
  ENABLE_AI_FRAUD_DETECTION: "true"
  ENABLE_BIOMETRIC_AUTH: "true"
  ENABLE_REMOTE_WORK_TRACKING: "true"
  ENABLE_AI_AGENT_MANAGEMENT: "true"
  ENABLE_HYBRID_COLLABORATION: "true"
  ENABLE_IOT_INTEGRATION: "true"
  ENABLE_PREDICTIVE_ANALYTICS: "true"
  
  # Performance Settings
  TARGET_RESPONSE_TIME_MS: "200"
  TARGET_AVAILABILITY_PERCENT: "99.9"
  MAX_CONCURRENT_REQUESTS: "1000"
  WORKER_PROCESSES: "4"
  
  # Compliance Settings
  FLSA_COMPLIANCE_ENABLED: "true"
  GDPR_COMPLIANCE_ENABLED: "true"
  OVERTIME_THRESHOLD_HOURS: "8.0"
  BREAK_AUTO_DEDUCTION: "true"
  MINIMUM_BREAK_MINUTES: "30"
  
  # Security Settings
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRE_MINUTES: "60"
  PASSWORD_MIN_LENGTH: "8"
  
  # Monitoring Settings
  METRICS_ENABLED: "true"
  PROMETHEUS_PORT: "9090"
  HEALTH_CHECK_INTERVAL: "30"
  
  # Integration Settings
  EDM_SERVICE_URL: "http://employee-data-management:8000"
  CV_SERVICE_URL: "http://computer-vision:8000"
  NOTIFICATION_SERVICE_URL: "http://notification-engine:8000"
  WORKFLOW_SERVICE_URL: "http://workflow-bpm:8000"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: apg-time-attendance
  labels:
    app.kubernetes.io/name: apg-time-attendance
    app.kubernetes.io/component: nginx-config
data:
  nginx.conf: |
    upstream app_server {
        server time-attendance-app:8000;
    }
    
    server {
        listen 80;
        server_name _;
        
        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        
        # Rate limiting
        limit_req_zone $binary_remote_addr zone=api:10m rate=100r/m;
        limit_req zone=api burst=20 nodelay;
        
        # Gzip compression
        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types text/plain text/css text/xml text/javascript application/json application/javascript application/xml+rss application/atom+xml image/svg+xml;
        
        # Health check endpoint
        location /health {
            access_log off;
            proxy_pass http://app_server/api/human_capital_management/time_attendance/health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        # API endpoints
        location /api/ {
            proxy_pass http://app_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Timeouts
            proxy_connect_timeout 5s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
            
            # Buffer settings
            proxy_buffering on;
            proxy_buffer_size 4k;
            proxy_buffers 8 4k;
        }
        
        # WebSocket support
        location /ws/ {
            proxy_pass http://app_server;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # WebSocket specific timeouts
            proxy_connect_timeout 7d;
            proxy_send_timeout 7d;
            proxy_read_timeout 7d;
        }
        
        # Static files (if any)
        location /static/ {
            alias /app/static/;
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
        
        # Metrics endpoint (protected)
        location /metrics {
            allow 10.0.0.0/8;
            allow 172.16.0.0/12;
            allow 192.168.0.0/16;
            deny all;
            
            proxy_pass http://app_server/metrics;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }