apiVersion: v1
kind: Namespace
metadata:
  name: apg-workflow
  labels:
    name: apg-workflow
    app.kubernetes.io/name: apg-workflow
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: apg-platform
    app.kubernetes.io/version: "1.0.0"
    managed-by: datacraft
  annotations:
    description: "APG Workflow Orchestration namespace"
    contact: "nyimbi@gmail.com"
    documentation: "https://docs.apg-platform.com/workflow"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: apg-workflow-quota
  namespace: apg-workflow
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: apg-workflow-limits
  namespace: apg-workflow
spec:
  limits:
  - type: Container
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: 50m
      memory: 64Mi
  - type: Pod
    max:
      cpu: "4"
      memory: 8Gi
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: apg-workflow-network-policy
  namespace: apg-workflow
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: apg-platform
    - podSelector:
        matchLabels:
          app.kubernetes.io/part-of: apg-platform
  - from: []
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 5432
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: apg-platform
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 5432