# Development Configuration for APG Payment Gateway
# This file contains development-specific overrides for local development

environment: development

# Database Configuration - Development
database:
  host: localhost
  port: 5432
  database: payment_gateway_dev
  username: pg_dev_user
  password: "dev_password_123"  # OK to hardcode in development
  ssl_mode: disable
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 3600
  echo: true  # Enable SQL logging in development

# Redis Configuration - Development
redis:
  host: localhost
  port: 6379
  password: ""
  db: 1  # Use different DB for development
  ssl: false
  max_connections: 10
  socket_timeout: 5
  socket_connect_timeout: 5

# Security Configuration - Development
security:
  secret_key: "dev-secret-key-not-for-production-use-only"
  jwt_secret: "dev-jwt-secret-not-for-production-use-only"
  jwt_expiry_hours: 48  # Longer expiry in development
  allowed_hosts:
    - "localhost"
    - "127.0.0.1"
    - "0.0.0.0"
    - "*.localhost"
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "http://localhost:8080"
    - "http://127.0.0.1:3000"
  rate_limit_per_minute: 10000  # Higher limit for development
  max_request_size_mb: 50  # Larger requests for testing
  require_https: false  # HTTP OK in development
  session_timeout_minutes: 120  # Longer sessions for development

# Logging Configuration - Development
logging:
  level: DEBUG
  file_path: "./logs/development.log"
  max_file_size_mb: 50
  backup_count: 3
  log_to_console: true
  log_to_file: true
  structured_logging: false  # Simple logging in development

# Monitoring Configuration - Development
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_port: 8080
  prometheus_enabled: false  # Disabled in development
  jaeger_enabled: false  # Disabled in development
  custom_metrics_enabled: false
  alert_thresholds:
    error_rate_percent: 50.0  # Higher tolerance in development
    response_time_ms: 5000
    fraud_score_threshold: 0.5
    success_rate_percent: 50.0

# Cache Configuration - Development
cache:
  default_ttl_seconds: 300  # Shorter TTL for development
  user_profile_ttl_seconds: 180
  fraud_rules_ttl_seconds: 60
  processor_health_ttl_seconds: 30
  analytics_cache_ttl_seconds: 120
  max_memory_mb: 64
  eviction_policy: "allkeys-lru"

# Webhook Configuration - Development
webhook:
  enabled: true
  max_retry_attempts: 2  # Fewer retries in development
  initial_retry_delay_seconds: 1
  max_retry_delay_seconds: 60
  timeout_seconds: 60
  batch_size: 10
  worker_threads: 2
  signature_algorithm: "hmac-sha256"
  delivery_timeout_hours: 1

# Fraud Detection Configuration - Development
fraud:
  enabled: true
  ml_models_enabled: false  # Disabled ML models in development for speed
  real_time_scoring: false
  score_threshold_review: 0.8
  score_threshold_decline: 0.95
  velocity_window_minutes: 120
  device_fingerprint_enabled: false
  geolocation_enabled: false
  whitelist_enabled: true
  blacklist_enabled: true
  model_refresh_hours: 168  # Weekly refresh

# API Configuration - Development
api:
  host: "0.0.0.0"
  port: 8000
  workers: 1  # Single worker for development
  max_connections: 100
  keepalive_timeout: 65
  client_timeout: 60
  api_version: "v1"
  docs_enabled: true  # Enable docs in development
  cors_enabled: true
  compression_enabled: false  # Disabled for easier debugging
  request_id_header: "X-Request-ID"

# Payment Processors Configuration - Development
processors:
  mpesa:
    api_url: "https://sandbox.safaricom.co.ke"
    api_key: "dev_consumer_key"
    secret_key: "dev_consumer_secret"
    webhook_secret: "dev_webhook_secret"
    sandbox_mode: true
    priority: 100
    rate_limits:
      requests_per_minute: 30
      requests_per_hour: 500
    timeout_seconds: 60
    retry_attempts: 2
    custom_config:
      business_short_code: "174379"  # Sandbox short code
      passkey: "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
      callback_url: "http://localhost:8000/api/v1/payments/webhooks/mpesa"
      result_url: "http://localhost:8000/api/v1/payments/webhooks/mpesa/result"
      queue_timeout_url: "http://localhost:8000/api/v1/payments/webhooks/mpesa/timeout"

  stripe:
    api_url: "https://api.stripe.com"
    api_key: "pk_test_51234567890"  # Test publishable key
    secret_key: "sk_test_51234567890"  # Test secret key
    webhook_secret: "whsec_test_123"
    sandbox_mode: true
    priority: 90
    rate_limits:
      requests_per_minute: 50
      requests_per_hour: 1000
    timeout_seconds: 60
    retry_attempts: 2
    custom_config:
      api_version: "2023-10-16"
      webhook_tolerance: 600  # More tolerance in development
      connect_timeout: 30
      read_timeout: 60

  adyen:
    api_url: "https://checkout-test.adyen.com"
    api_key: "AQE1hmfuXNWTK0Qc+iSEnz5LMz4="  # Test API key
    secret_key: "adyen_test_secret"
    webhook_secret: "adyen_webhook_secret"
    sandbox_mode: true
    priority: 85
    rate_limits:
      requests_per_minute: 75
      requests_per_hour: 1500
    timeout_seconds: 60
    retry_attempts: 2
    custom_config:
      merchant_account: "TestMerchant"
      api_version: "v70"

  paypal:
    api_url: "https://api.sandbox.paypal.com"
    api_key: "AYSq3RDGsmBLJE-otTkBtM-jBRd1TCQwFf9RGfwddNXWz0uFU9ztymylOhRS"  # Test client ID
    secret_key: "EGnHDxD_qRPdaLdHszzI0LvF0hMxhY2Z7j_v2FZs7r8YnD5qL5x5xX9xZ5q5"  # Test secret
    webhook_secret: "paypal_webhook_secret"
    sandbox_mode: true
    priority: 80
    rate_limits:
      requests_per_minute: 50
      requests_per_hour: 1000
    timeout_seconds: 60
    retry_attempts: 2
    custom_config:
      webhook_id: "1234567890"
      return_url: "http://localhost:3000/payments/success"
      cancel_url: "http://localhost:3000/payments/cancel"

# Custom Configuration - Development
custom:
  # Feature flags - Development (all enabled for testing)
  features:
    smart_completion_enabled: true
    conversational_payments_enabled: true
    immersive_analytics_enabled: true
    real_time_notifications_enabled: true
    advanced_fraud_detection_enabled: false  # Disabled for performance
    multi_currency_support_enabled: true
    debug_mode_enabled: true
    test_mode_enabled: true
    mock_processors_enabled: false
    
  # Regional settings - Development
  regional:
    default_country: "KE"
    default_currency: "KES"
    default_timezone: "Africa/Nairobi"
    supported_languages:
      - "en"
      - "sw"
    
  # Business rules - Development (relaxed for testing)
  business_rules:
    max_transaction_amount_usd: 1000  # Lower limit for development
    min_transaction_amount_usd: 0.01
    daily_transaction_limit_usd: 5000
    fraud_review_queue_enabled: false  # Disabled for easier testing
    auto_capture_enabled: true
    auto_capture_delay_hours: 1  # Faster capture for testing
    test_transactions_enabled: true
    
  # Integration settings - Development
  integrations:
    slack_webhook_url: ""  # Empty in development
    email_service_api_key: "test_email_key"
    sms_service_api_key: "test_sms_key"
    push_notification_service_key: "test_push_key"
    mock_external_services: true
    
  # Performance settings - Development
  performance:
    max_concurrent_transactions: 100
    transaction_timeout_seconds: 600  # Longer timeout for debugging
    batch_processing_size: 10
    async_webhook_processing: false  # Synchronous for easier debugging
    database_query_timeout_seconds: 60
    cache_warm_up_enabled: false
    
  # Development tools
  development:
    hot_reload_enabled: true
    debug_toolbar_enabled: true
    profiling_enabled: true
    sql_query_logging: true
    request_response_logging: true
    mock_data_generation: true
    test_data_seeding: true
    swagger_ui_enabled: true
    
  # Testing settings
  testing:
    create_test_merchants: true
    create_test_transactions: true
    populate_analytics_data: true
    enable_test_webhooks: true
    mock_fraud_detection: true
    bypass_rate_limiting: true
    
  # Local development paths
  paths:
    log_directory: "./logs"
    data_directory: "./data"
    temp_directory: "./tmp"
    upload_directory: "./uploads"
    static_files_directory: "./static"