"""APG runtime shim — base classes for generated agent and capability stubs.

These are minimal dependency-free base classes that generated code can
import without requiring the full APG platform to be installed.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class AgentContext:
	"""Runtime context passed to agent invocations."""
	tenant_id: str = "default"
	user_id: str = "anonymous"
	session_id: str = ""
	metadata: dict[str, Any] = field(default_factory=dict)


class AgentBase:
	"""Base class for generated APG agent adapter stubs.

	Subclasses are generated by the APG compiler from `agent` declarations.
	They hold the agent's declared metadata and provide an `invoke` method
	that routes to the configured runtime.

	Provider command contract:
	    The env var ``APG_AGENT_<RUNTIME>_PROVIDER_COMMAND`` (falling back to
	    ``APG_AGENT_PROVIDER_COMMAND``) names an executable that receives on
	    stdin a JSON object::

	        {"agent": {"name": "...", "role": "...", "model": "..."},
	         "input": "<prompt>",
	         "context": {"tenant_id": "...", "user_id": "..."}}

	    and must write to stdout a JSON object::

	        {"output": "<response text>"}

	Attributes:
	    name:    Agent name as declared in the APG source.
	    role:    Agent role description.
	    model:   LLM model identifier (e.g. 'openai:gpt-4.1-mini').
	    runtime: Runtime identifier (e.g. 'codex', 'claude_code').
	    system:  System prompt for the agent.
	    capabilities: Declared capability identifiers (immutable; subclasses replace).
	    tools:         Declared tool identifiers (immutable; subclasses replace).
	    configuration: Runtime configuration map (subclasses replace entirely; do NOT mutate base).
	"""

	name: str = ""
	role: str = ""
	model: str = ""
	runtime: str = "codex"
	system: str = ""
	capabilities: tuple[str, ...] = ()
	tools: tuple[str, ...] = ()
	# Note: do NOT use a mutable default here — subclasses replace this at the class level
	configuration: "dict[str, Any]" = {}  # type: ignore[assignment]

	async def invoke(self, prompt: str, context: AgentContext | None = None) -> str:
		"""Invoke the agent with a prompt.

		The default implementation raises NotImplementedError. Generated stubs
		override this to route to the declared runtime via the agent adapter.
		"""
		env_key = f"APG_AGENT_{self.runtime.upper()}_PROVIDER_COMMAND"
		cmd = (
			__import__("os").environ.get(env_key)
			or __import__("os").environ.get("APG_AGENT_PROVIDER_COMMAND")
		)
		if not cmd:
			raise RuntimeError(
				f"Agent '{self.name}': set {env_key} to configure the "
				f"{self.runtime!r} runtime provider command."
			)
		raise NotImplementedError(
			f"Agent '{self.name}' has no runtime wired up. "
			f"Set {env_key} to configure."
		)

	def __repr__(self) -> str:
		return f"<{type(self).__name__} name={self.name!r} model={self.model!r}>"
