"""APG runtime shim — base classes for generated agent and capability stubs.

These are minimal dependency-free base classes that generated code can
import without requiring the full APG platform to be installed.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class AgentContext:
	"""Runtime context passed to agent invocations."""
	tenant_id: str = "default"
	user_id: str = "anonymous"
	session_id: str = ""
	metadata: dict[str, Any] = field(default_factory=dict)


class AgentBase:
	"""Base class for generated APG agent adapter stubs.

	Subclasses are generated by the APG compiler from `agent` declarations.
	They hold the agent's declared metadata and provide an `invoke` method
	that routes to the configured runtime.

	Attributes:
	    name:    Agent name as declared in the APG source.
	    role:    Agent role description.
	    model:   LLM model identifier (e.g. 'openai:gpt-4.1-mini').
	    runtime: Runtime identifier (e.g. 'codex', 'claude_code').
	"""

	name: str = ""
	role: str = ""
	model: str = ""
	runtime: str = "codex"
	system: str = ""
	capabilities: list[str] = []
	tools: list[str] = []
	configuration: dict[str, Any] = {}

	async def invoke(self, prompt: str, context: AgentContext | None = None) -> str:
		"""Invoke the agent with a prompt.

		The default implementation raises NotImplementedError. Generated stubs
		override this to route to the declared runtime via the agent adapter.
		"""
		raise NotImplementedError(
			f"Agent '{self.name}' has no runtime wired up. "
			f"Set APG_AGENT_{self.runtime.upper()}_PROVIDER_COMMAND to configure."
		)

	def __repr__(self) -> str:
		return f"<{type(self).__name__} name={self.name!r} model={self.model!r}>"
