# Crawlee Enhanced Configuration Example
# ========================================
# Advanced configuration for content extraction using Crawlee

# Core search parameters
mode: "crawlee"
query: "Horn of Africa humanitarian crisis"
engines:
  - "google"
  - "bing"
  - "duckduckgo"
max_results: 50
max_results_per_engine: 20

# Content extraction settings
download_content: true
extract_content: true
min_content_length: 500
preferred_extraction_method: "trafilatura"

# Geographic settings
target_countries:
  - "ET"
  - "SO"
  - "ER"
  - "DJ"
  - "SD"
  - "SS"
enable_conflict_detection: true
escalation_threshold: 0.8

# Performance settings
timeout: 60
max_concurrent: 5  # Lower for content extraction
retry_attempts: 3
rate_limit_delay: 2.0
enable_stealth: true

# Quality settings (high standards for content)
min_relevance_score: 0.7
enable_quality_filtering: true
min_quality_score: 0.8
deduplicate_results: true

# Output settings
output_format: "json"
verbose: false
quiet: false
show_progress: true

# Advanced settings
enable_alerts: false
batch_mode: false
monitor_mode: false